import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/banner";
import Header from "../components/header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Banner />

      <main className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
